### ISSUE TITLE
ntrain < dimension error

### ISSUE THREAD

**Issue by billybyun** [neurodata/LOL-paper#19]
Error occurs in LOL.m : Proj{i}.V = V(:,1:temp)
when ntrain < D. Can be fixed by not using the 'economy size' svd.

**Comment by jovo** [comment]
i don't think so.
can you post the code that led to this error?

On Tue, Jun 24, 2014 at 8:44 PM, Billy Byun notifications@github.com
wrote:

>  Error occurs in LOL.m : Proj{i}.V = V(:,1:temp)
> when ntrain < D. Can be fixed by not using the 'economy size' svd.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/LOL/issues/19.

## 

perhaps consider allowing the quest for eudaimonia to guide you
openconnecto.me, jovo.me

**Comment by billybyun** [comment]
Ok. I got this bug about two weeks ago though. I will check again and post.

On Tue, Jun 24, 2014 at 9:41 PM, joshua vogelstein <notifications@github.com

> wrote:
> 
> i don't think so.
> can you post the code that led to this error?
> 
> On Tue, Jun 24, 2014 at 8:44 PM, Billy Byun notifications@github.com
> wrote:
> 
> > Error occurs in LOL.m : Proj{i}.V = V(:,1:temp)
> > when ntrain < D. Can be fixed by not using the 'economy size' svd.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jovo/LOL/issues/19.
> 
> ## 
> 
> perhaps consider allowing the quest for eudaimonia to guide you
> openconnecto.me, jovo.me
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/LOL/issues/19#issuecomment-47051724.

## 

Billy Byun
Biomedical Engineering and Electrical & Computer Engineering
BSE. Duke University '14
