### ISSUE TITLE
add LOL_loocv

### ISSUE THREAD

**Issue by jovo** [neurodata/LOL-paper#21]
input: X,Y, LOLparms
output: Lhat, Yhat for each cv, Proj matrix for each cv

**Comment by tyler-tomita** [comment]
Line 28 has an error: disagree(i,j,k) = Yhats{i}{j}(k)~=Y(i). 

The reference to Y(i) should be Y{i} with curly braces instead.

The whole things runs, but all of the Yhats and Lhats are NaNs. I get a bunch of these messages:
"the linear classifier barfed 
The following error occurred converting from cell to double:
Error using double
Conversion to double from cell is not possible."

I assigned parms just as you instructed. Xrank_pca is nx3, Y is an nx1 cell array of strings.

**Comment by jovo** [comment]
try now?

On Thu, Feb 26, 2015 at 6:12 PM, ttomita notifications@github.com wrote:

>  Line 28 has an error: disagree(i,j,k) = Yhats{i}{j}(k)~=Y(i).
> 
> The reference to Y(i) should be Y{i} with curly braces instead.
> 
> The whole things runs, but all of the Yhats and Lhats are NaNs. I get a
> bunch of these messages:
> "the linear classifier barfed
> The following error occurred converting from cell to double:
> Error using double
> Conversion to double from cell is not possible."
> 
> I assigned parms just as you instructed. Xrank_pca is nx3, Y is an nx1
> cell array of strings.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/LOL/issues/21#issuecomment-76295881.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
Awesome it works

**Comment by jovo** [comment]
love it!!!!  whenever you get a chance, i'm super stoked to see performance
on qing's data....

On Sat, Feb 28, 2015 at 1:52 PM, ttomita notifications@github.com wrote:

>  Awesome it works
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/LOL/issues/21#issuecomment-76539784.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
