### ISSUE TITLE
i can't label issues here because i'm not a contributor?

### ISSUE THREAD

**Issue by ronboger** [neurodata/LOL-paper#43]

**Comment by jovo** [comment]
fixed

On Tue, Sep 1, 2015 at 2:27 PM, ron boger notifications@github.com wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/LOL/issues/43.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, calendar
https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York
