### ISSUE TITLE
computational efficiency

### ISSUE THREAD

**Issue by jovo** [neurodata/LOL-paper#50]
check this section, see if i did anything dumb?
if so, tell me?

**Comment by zheng-da** [comment]
could you fix the bibliography?
you use "../../../../Other/latex/library.bib", which isn't a path in the repo.

**Comment by jovo** [comment]
sorry, fixed.

**Comment by zheng-da** [comment]
actually, i have some small comments in this and the following sections. Please see the comments in the attached pdf.
[LOL-comments.pdf](https://github.com/neurodata/LOL/files/293900/LOL-comments.pdf)

**Comment by zheng-da** [comment]
Do you want to have randomized PCA implemented, right?
I'm checking the algorithms for QR decomposition. It's not very difficult to implement, but I'm not sure if the data access pattern required by the algorithm can run on SSDs efficiently.

**Comment by jovo** [comment]
all your comments are correct.
please make the changes in the text.

in terms of the linear scale-up, i think the IM linear increase means that
it must be, right?

On Wed, Jun 1, 2016 at 6:38 PM, Da Zheng notifications@github.com wrote:

> actually, i have some small comments in this and the following sections.
> Please see the comments in the attached pdf.
> LOL-comments.pdf
> https://github.com/neurodata/LOL/files/293900/LOL-comments.pdf
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/LOL/issues/50#issuecomment-223051567, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcqH52go9xGoT1S1WCHlzjRlI9AnRks5qHbWHgaJpZM4IrV4z
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
oh, right, i forgot that you did just random projection, rather than
randomized svd.

can you fix text accordingly?
i'd rather have a good implementation of the sparse random projection
algorithm first.

also, please update the computational theory to include random projection
(and just comment out random svd for now).

thank you!

On Wed, Jun 1, 2016 at 6:41 PM, Da Zheng notifications@github.com wrote:

> Do you want to have randomized PCA implemented, right?
> I'm checking the algorithms for QR decomposition. It's not very difficult
> to implement, but I'm not sure if the data access pattern required by the
> algorithm can run on SSDs efficiently.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/LOL/issues/50#issuecomment-223052320, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcjFGIJDePs3ZeEUwhJPZgIZZu5Cgks5qHbYjgaJpZM4IrV4z
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by zheng-da** [comment]
Figure 4(a) shows the scaleup with the problem size. The computation time is supposed to increase linearly if the implementation is correct.
We probably should have an experiment to show speedup with the number of threads given a fixed problem size.

**Comment by jovo** [comment]
i thought it showed both, the in memory shows scale up, and the em shows scale out, both linearly?

**Comment by zheng-da** [comment]
It seems to me that scaleup can have multiple meanings.

In the context of hardware architecture, when you scale up vs. scale out, it usually means the followings:
To scale horizontally (or scale out/in) means to add more nodes to (or remove nodes from) a system, such as adding a new computer to a distributed software application.
To scale vertically (or scale up/down) means to add resources to (or remove resources from) a single node in a system, typically involving the addition of CPUs or memory to a single computer.
I get this definition from Wiki (https://en.wikipedia.org/wiki/Scalability#Horizontal_and_vertical_scaling). This is also my understanding of scale up and scale out.

In the context of parallel computing, we have a concept of scaleup vs. speedup.
Scaleup is the ability to keep the same performance levels (response time) when both workload (transactions) and resources (CPU, memory) increase proportionally.
Speedup is the effect of applying an increasing number of resources to a fixed amount of work to achieve a proportional reduction in execution times
I copy the definition from this link (https://exploredatabase.blogspot.com/2013/11/scaleup-and-speedup.html).

Figure 4(a) doesn't show either definition of scaleup. However, this isn't a computer science or parallel computing paper. I'm not sure if we should show both scaleup and speedup.

**Comment by jovo** [comment]
ok, from my conversations with randal, i understood "scale up" a bit more
generally.
specifically, as the problem size gets bigger, it consumes more resources
(RAM),
so the linear increase in time as problem sizes gets bigger means that we
are recruiting RAM as efficiently as possible.

how would you run an experiment to test your definition of scale up?

On Wed, Jun 1, 2016 at 8:56 PM, Da Zheng notifications@github.com wrote:

> It seems to me that scaleup can have multiple meanings.
> 
> In the context of hardware architecture, when you scale up vs. scale out,
> it usually means the followings:
> To scale horizontally (or scale out/in) means to add more nodes to (or
> remove nodes from) a system, such as adding a new computer to a distributed
> software application.
> To scale vertically (or scale up/down) means to add resources to (or
> remove resources from) a single node in a system, typically involving the
> addition of CPUs or memory to a single computer.
> I get this definition from Wiki (
> https://en.wikipedia.org/wiki/Scalability#Horizontal_and_vertical_scaling).
> This is also my understanding of scale up and scale out.
> 
> In the context of parallel computing, we have a concept of scaleup vs.
> speedup.
> Scaleup is the ability to keep the same performance levels (response time)
> when both workload (transactions) and resources (CPU, memory) increase
> proportionally.
> Speedup is the effect of applying an increasing number of resources to a
> fixed amount of work to achieve a proportional reduction in execution times
> I copy the definition from this link (
> https://exploredatabase.blogspot.com/2013/11/scaleup-and-speedup.html).
> 
> Figure 4(a) doesn't show either definition of scaleup. However, this isn't
> a computer science or parallel computing paper.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/LOL/issues/50#issuecomment-223090734, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcluyLK_nStTeAQFQucBgr3WkQAROks5qHdXSgaJpZM4IrV4z
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by zheng-da** [comment]
I think your definition of scaleup is also reasonable.

However, Figure 4(A) doesn't indicate the following statement because the figure doesn't vary the number of threads.
Our parallel in memory implementation scales-up optimally (linearly) with the number of threads, requiring O(npd/T) flops for LOL , where T is the number of threads. Our parallel semi-external memory implementation scales-out optimally (linearly) as well.

To show scaleup in the context of parallel computing, we should increase the problem size and the number of threads together. If we can achieve linear scaleup, we should see a flat line. Does it sound reasonable?

**Comment by jovo** [comment]
how is it possible for us to have the result we have if we aren't achieving
a linear scaleup?

anyway, i'd support that experiment, i just can't explain the current
result in any other way,
but maybe just cuz i don't understand enough stuff...

On Wed, Jun 1, 2016 at 9:23 PM, Da Zheng notifications@github.com wrote:

> I think your definition of scaleup is also reasonable.
> 
> However, Figure 4(A) doesn't indicate the following statement because the
> figure doesn't vary the number of threads.
> Our parallel in memory implementation scales-up optimally (linearly) with
> the number of threads, requiring O(npd/T) flops for LOL , where T is the
> number of threads. Our parallel semi-external memory implementation
> scales-out optimally (linearly) as well.
> 
> To show scaleup in the context of parallel computing, we should increase
> the problem size and the number of threads together. If we can achieve
> linear scaleup, we should see a flat line. Does it sound reasonable?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/LOL/issues/50#issuecomment-223097755, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjctIe_CbUAYHFVxqubONzowM-PP2Rks5qHdwngaJpZM4IrV4z
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by zheng-da** [comment]
I think we'll achieve linear scaleup. It's usually easier to achieve linear scaleup than linear speedup.
I'll run the experiment. Let's see which experiment should be included in the paper.

**Comment by zheng-da** [comment]
BTW, if we increase the problem size with the number of threads, we can only vary the problem size from 1M-48M because we have only 48 CPU cores.

**Comment by jovo** [comment]
that's fine.

On Wed, Jun 1, 2016 at 9:41 PM, Da Zheng notifications@github.com wrote:

> BTW, if we increase the problem size with the number of threads, we can
> only vary the problem size from 1M-48M because we have only 48 CPU cores.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/LOL/issues/50#issuecomment-223102492, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcpVquK-Yd6W0L6GhS93FXTG7TdZlks5qHeCFgaJpZM4IrV4z
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by zheng-da** [comment]
I was looking at randomized SVD. I just realized that we can implement randomized SVD in FlashR for a data matrix, where n=2000 and p>1M.
In this case, I can totally use R's QR factorization to handle the matrix.
I'll need a FlashR implementation of QR decomposition if we want to run randomized SVD on a very large sparse matrix such as sparse graphs.

However, for a n x p data matrix, I'm not sure if randomized SVD is worth it, unless we use sparse random projection. It's computational expensive to generate a p x 2d Gaussian matrix. We also need two matrix multiplication on the data matrix A, which is also very expensive.

Randomized SVD on a large sparse matrix totally makes sense!

**Comment by jovo** [comment]
yah, we always probably want to use very sparse random projection, both on
its own, and as part of randomized svd, when we have a dense p x d matrix.

On Thursday, June 2, 2016, Da Zheng notifications@github.com wrote:

> I was looking at randomized SVD. I just realized that we can implement
> randomized SVD in FlashR for a data matrix, where n=2000 and p>1M.
> In this case, I can totally use R's QR factorization to handle the matrix.
> I'll need a FlashR implementation of QR decomposition if we want to run
> randomized SVD on a very large sparse matrix such as sparse graphs.
> 
> However, for a n x p data matrix, I'm not sure if randomized SVD is worth
> it, unless we use sparse random projection. It's computational expensive to
> generate a p x 2d Gaussian matrix. We also need two matrix multiplication
> on the data matrix A, which is also very expensive.
> 
> Randomized SVD on a large sparse matrix totally makes sense!
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/LOL/issues/50#issuecomment-223165835, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcvBtXTv-gqFZQZVXudnaGdHOMlSvks5qHiYXgaJpZM4IrV4z
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
