### ISSUE TITLE
da edits

### ISSUE THREAD

**Issue by jovo** [neurodata/LOL-paper#52]
- [x] add all FlashX citations, including FlashGraph
- [x] in Fig4, what did you use for c?  please specify.

**Comment by zheng-da** [comment]
what is c in Fig 4? did you add another subfigure?

BTW, In the caption of Fig 4, LOL in external memory takes 23 minutes to find the embedding on a dataset with 64M dimension, which is 1TB (64M \* 2000 \* 8), I think.

**Comment by jovo** [comment]
c is the sparsity constant in your sparse random projections.

any errors you find just fix and make a pull request or push the changes
directly.

On Sat, Jun 18, 2016 at 2:53 PM, Da Zheng notifications@github.com wrote:

> what is c in Fig 4? did you add another subfigure?
> 
> BTW, In the caption of Fig 4, LOL in external memory takes 23 minutes to
> find the embedding on a dataset with 64M dimension, which is 1TB (64M *
> 2000 \* 8), I think.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/LOL/issues/52#issuecomment-226959004, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcgeHlkW4F2vDizbH55QrioSuNDdJks5qND6ngaJpZM4I41ax
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by zheng-da** [comment]
please check if the description is clear
