### ISSUE TITLE
da stuff

### ISSUE THREAD

**Issue by jovo** [neurodata/LOL-paper#56]
- [x] fix LOL code to subtract class conditional means
- [x] push experiments code to this repo
- [x] add LR-LDA (class conditional mean subtract followed by svd)
- [x] send updated csv file for fig 4B including 4 different strategies (PCA, LOL, LAL, LR-LDA)
- [x] send new timing results for LOL, LAL, & PCA

**Comment by zheng-da** [comment]
``` R
library(FlashR)
library(MASS)
source("Rpkg/R/LOL.R")
fm.set.test.na(FALSE)
p <- 16000000
n <- 1000
red.p <- 1
labels <- rep.int(0, n * 2)
labels[(n+1):(2*n)] <- 1

for (i in 1:10) {
    mu <- 4/sqrt(seq.int(1, 2*p, 2))
    sigma.vec <- 1000/sqrt(seq.int(p, 1, -1))
    # generate the training dataset
    #mat1 <- rmvnorm(n, mu, diag(sigma.vec))
    mat1 <- fm.rnorm.matrix(nrow=n, ncol=p, in.mem=TRUE)
    mat1 <- sweep(mat1, 2, sqrt(sigma.vec), "*")
    mat1 <- sweep(mat1, 2, mu, "+")
    #mat2 <- rmvnorm(n, -mu, diag(sigma.vec))
    mat2 <- fm.rnorm.matrix(nrow=n, ncol=p, in.mem=TRUE)
    mat2 <- sweep(mat2, 2, sqrt(sigma.vec), "*")
    mat2 <- sweep(mat2, 2, -mu, "+")
    mat <- fm.rbind(mat1, mat2)
    # generate the testing dataset
    #test1 <- rmvnorm(100, mu, diag(sigma.vec))
    test1 <- fm.rnorm.matrix(nrow=100, ncol=p, in.mem=TRUE)
    test1 <- sweep(test1, 2, sqrt(sigma.vec), "*")
    test1 <- sweep(test1, 2, mu, "+")
    #test2 <- rmvnorm(100, -mu, diag(sigma.vec))
    test2 <- fm.rnorm.matrix(nrow=100, ncol=p, in.mem=TRUE)
    test2 <- sweep(test2, 2, sqrt(sigma.vec), "*")
    test2 <- sweep(test2, 2, -mu, "+")
    test <- fm.rbind(test1, test2)

    mat1 <- NULL
    mat2 <- NULL
    test1 <- NULL
    test2 <- NULL
    gc()

    for (red.p in c(10, 50, 100, 500)) {
        cat("#reduced dim:", red.p)

        #LOL
        proj <- LOL(t(mat), fm.conv.R2FM(as.integer(labels)), red.p, type="svd")
        mat.p <- mat %*% proj
        test.p <- test %*% proj
        res <- lda(as.matrix(fm.conv.FM2R(mat.p)), as.factor(labels))
        pred <- predict(object=res, newdata=as.matrix(fm.conv.FM2R(test.p)))

        # measure the accuracy
        truth <- rep.int(1, length(pred$class))
        truth[(length(truth)/2 + 1):length(truth)]<-2
        cat("LOL:", sum((as.integer(pred$class) - truth) != 0)/length(pred$class), "\n")

        #LAL
        proj <- LOL(t(mat), fm.conv.R2FM(as.integer(labels)), red.p, type="rand_sparse")
        mat.p <- mat %*% proj
        test.p <- test %*% proj
        res <- lda(as.matrix(fm.conv.FM2R(mat.p)), as.factor(labels))
        pred <- predict(object=res, newdata=as.matrix(fm.conv.FM2R(test.p)))

        # measure the accuracy
        truth <- rep.int(1, length(pred$class))
        truth[(length(truth)/2 + 1):length(truth)]<-2
        cat("LAL:", sum((as.integer(pred$class) - truth) != 0)/length(pred$class), "\n")
        proj <- NULL
        gc()

        #PCA
        mu <- colMeans(mat)
        center.mat <- sweep(mat, 2, mu, "-")
        res <- fm.svd(center.mat, red.p, red.p)
        mat.p <- mat %*% res$v
        test.p <- test %*% res$v
        res <- lda(as.matrix(fm.conv.FM2R(mat.p)), as.factor(labels))
        pred <- predict(object=res, newdata=as.matrix(fm.conv.FM2R(test.p)))

        # measure the accuracy
        truth <- rep.int(1, length(pred$class))
        truth[(length(truth)/2 + 1):length(truth)]<-2
        cat("PCA:", sum((as.integer(pred$class) - truth) != 0)/length(pred$class), "\n")
        mu <- NULL
        center.mat <- NULL
        gc()

        #LR-LDA
        gr.sum <- fm.groupby(mat, 2, fm.as.factor(fm.conv.R2FM(as.integer(labels)), 2), fm.bo.add)
        counts <- as.data.frame(table(as.integer(labels)))
        gr.mean <- fm.mapply.col(gr.sum, counts$Freq, fm.bo.div, FALSE)
        mean.idxs <- as.integer(labels) + 1
        mean.list <- list()
        for (i in 1:length(labels))
            mean.list[[i]] <- gr.mean[mean.idxs[i],]
        mean.mat <- fm.rbind.list(mean.list)
        res <- fm.svd(mat - mean.mat, nv=red.p, nu=0)
        mat.p <- mat %*% res$v
        test.p <- test %*% res$v
        res <- lda(as.matrix(fm.conv.FM2R(mat.p)), as.factor(labels))
        pred <- predict(object=res, newdata=as.matrix(fm.conv.FM2R(test.p)))

        # measure the accuracy
        truth <- rep.int(1, length(pred$class))
        truth[(length(truth)/2 + 1):length(truth)]<-2
        cat("LR-LDA:", sum((as.integer(pred$class) - truth) != 0)/length(pred$class), "\n")
        gr.sum <- NULL
        gr.mean <- NULL
        mean.list <- NULL
        res <- NULL
        gc()

    } # vary # reduced dimensions

    mat <- NULL
    test <- NULL
    gc()

} # run experiments 10 times
```

**Comment by zheng-da** [comment]
@jovo I have a few questions. I just want to double check if I'm doing the right thing.

For PCA, what projection matrix should we use for the testing data? We can run SVD on the testing data and use the output of the SVD as the projection matrix. We can also use the result of SVD on the training data. I guess it doesn't really matter because we assume both training data and testing data are from the same distribution. In the case of SVD, I feel it's a little weird to use the projection matrix from the training data on the testing data since we can compute the projection matrix from the testing data directly.

The same question goes to LR-LDA. Do we use the projection matrix from the training data on the testing data? I guess in this case we have to do it. Otherwise, we don't even know the class condition mean for the testing data.

The other question is which matrix we should project. The original training and testing matrices X or the centered matrices (X_i - X_ba) or (X_i - X_k_ba)? X_k_ba is the mean in class k.

**Comment by jovo** [comment]
1) always use _training_ data for learning projection and projecting.
in real data, sometimes there will only be 1 test sample,
so we can't rely on test data, in general.

2) we project the test data, we don't know the means for the test data, so
we can't estimate them and use them.

does that help?

On Wed, Jul 6, 2016 at 8:48 PM, Da Zheng notifications@github.com wrote:

> @jovo https://github.com/jovo I have a few questions. I just want to
> double check if I'm doing the right thing.
> 
> For PCA, what projection matrix should we use for the testing data? We can
> run SVD on the testing data and use the output of the SVD as the projection
> matrix. We can also use the result of SVD on the training data. I guess it
> doesn't really matter because we assume both training data and testing data
> are from the same distribution. In the case of SVD, I feel it's a little
> weird to use the projection matrix from the training data on the testing
> data since we can compute the projection matrix from the testing data
> directly.
> 
> The same question goes to LR-LDA. Do we use the projection matrix from the
> training data on the testing data? I guess in this case we have to do it.
> Otherwise, we don't even know the class condition mean for the testing data.
> 
> The other question is which matrix we should project. The original
> training and testing matrices X or the centered matrices (X_i - X_ba) or
> (X_i - X_k_ba)? X_k_ba is the mean in class k.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/LOL/issues/56#issuecomment-230949613, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcnfkcpY7OqLhHeqxckV-yOfkcxgEks5qTEztgaJpZM4JFddT
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by zheng-da** [comment]
Thanks. Then I'm doing the right except for PCA. I have fixed it.

So we only project the original training and testing matrix, right?

I don't quite understand the second part of your second comment. Since we project the original training and testing data, why do we need to estimate the mean of the test data and how do we use them?

**Comment by zheng-da** [comment]
BTW, LR-LDA is useless. Even if we reduce the dimension size to 500, the classification error is still 50%. unless I did something very wrong in the implementation.

**Comment by jovo** [comment]
LR-LDA: that is what i expected.

we do not need to estimate the mean of the test data, and we do not use them.
sorry, i had a typo

**Comment by zheng-da** [comment]
Here shows one experiment result for different reduced dimension sizes.
Before I didn't shift the training data to the center when I run PCA.
It turns out this matters even for the dataset generated from the normal distribution with 0 mean.
After I correct the mistake, PCA works fine when the reduced dimension size is 500. almost as good as LAL.
I'm still running the experiment.
@jovo If you think the result isn't reasonable, I'll stop it and debug it.

```
#reduced dim: 10[1] "svd"
LOL: 0.05
LAL: 0.055
PCA: 0.49
LR-LDA: 0.495
#reduced dim: 50[1] "svd"
LOL: 0.045
LAL: 0.055
PCA: 0.26
LR-LDA: 0.49
#reduced dim: 100[1] "svd"
LOL: 0.045
LAL: 0.075
PCA: 0.185
LR-LDA: 0.495
#reduced dim: 500[1] "svd"
LOL: 0.045
LAL: 0.1
PCA: 0.095
LR-LDA: 0.535
```

**Comment by jovo** [comment]
seems reasonable to me.

On Thu, Jul 7, 2016 at 8:24 PM, Da Zheng notifications@github.com wrote:

> Here shows one experiment result for different reduced dimension sizes.
> Before I didn't shift the training data to the center when I run PCA.
> It turns out this matters even for the dataset generated from the normal
> distribution with 0 mean.
> After I correct the mistake, PCA works fine when the reduced dimension
> size is 500. almost as good as LAL.
> I'm still running the experiment.
> @jovo https://github.com/jovo If you think the result isn't reasonable,
> I'll stop it and debug it.
> 
> #reduced dim: 10[1] "svd"
> LOL: 0.05
> LAL: 0.055
> PCA: 0.49
> LR-LDA: 0.495
> #reduced dim: 50[1] "svd"
> LOL: 0.045
> LAL: 0.055
> PCA: 0.26
> LR-LDA: 0.49
> #reduced dim: 100[1] "svd"
> LOL: 0.045
> LAL: 0.075
> PCA: 0.185
> LR-LDA: 0.495
> #reduced dim: 500[1] "svd"
> LOL: 0.045
> LAL: 0.1
> PCA: 0.095
> LR-LDA: 0.535
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/LOL/issues/56#issuecomment-231245241, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcvftR5hLM9uV9sLZRJTtYxAaQ2bkks5qTZjMgaJpZM4JFddT
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by zheng-da** [comment]
The runtime performance is in the following 6 files:
FM-LAL-EM.n-1000.d-100.csv
FM-LAL-IM.n-1000.d-100.csv
FM-LOL-EM.n-1000.d-100.csv
FM-LOL-IM.n-1000.d-100.csv
FM-PCA-EM.n-1000.d-100.csv
FM-PCA-IM.n-1000.d-100.csv

**Comment by zheng-da** [comment]
The new accuracy results are in FM.n-1000.p-16000000.csv
